import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Sparkles, Download, BookmarkPlus, Loader2 } from "lucide-react";
import { PageHeader, CompletenessBar } from "@/components/page-header";
import { suggestedQueries } from "@/data/sample";
import { FarmerSheet } from "@/components/farmer-sheet";
import {
  Dialog, DialogContent, DialogDescription, DialogFooter,
  DialogHeader, DialogTitle, DialogTrigger,
} from "@/components/ui/dialog";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { askIntelligence, type IntelligenceAnswer } from "@/server/ai.functions";
import { getAiErrorMessage } from "@/lib/ai-errors";
import { toast } from "sonner";
import { getFarmers } from "@/server/farmers.functions";

export const Route = createFileRoute("/intelligence")({
  head: () => ({
    meta: [
      { title: "Intelligence · FarmIQ" },
      { name: "description", content: "Ask plain-language questions and get traceable answers from your farmer data." },
    ],
  }),
  loader: () => getFarmers(),
  component: IntelligencePage,
});

function IntelligencePage() {
  const farmers = Route.useLoaderData();
  const [query, setQuery] = useState("");
  const [loading, setLoading] = useState(false);
  const [answer, setAnswer] = useState<IntelligenceAnswer | null>(null);

  const matchedFarmers = answer
    ? farmers.filter((f) => answer.farmerIds.includes(f.id))
    : [];

  async function handleAsk(nextQuery = query) {
    const trimmed = nextQuery.trim();
    if (!trimmed) { toast.error("Enter a question first."); return; }
    setLoading(true);
    try {
      const result = await askIntelligence({ data: { query: trimmed } });
      setAnswer(result);
      setQuery(trimmed);
    } catch (error) {
      toast.error(getAiErrorMessage(error));
    } finally {
      setLoading(false);
    }
  }

  return (
    <div>
      <PageHeader
        title="Intelligence"
        description="Ask FarmIQ a question in plain English. Answers are generated by OpenRouter using your farmer dataset."
      />

      <Card className="shadow-none border">
        <CardContent className="p-6">
          <div className="flex items-center gap-2 rounded-lg border bg-card px-3 py-2 focus-within:ring-2 focus-within:ring-primary/30 focus-within:border-primary">
            <Sparkles className="h-4 w-4 text-primary" />
            <Input
              value={query}
              onChange={(e) => setQuery(e.target.value)}
              onKeyDown={(e) => { if (e.key === "Enter") void handleAsk(); }}
              placeholder="Ask FarmIQ anything about your farmers…"
              className="border-0 shadow-none focus-visible:ring-0 px-0 h-10 text-base"
              disabled={loading}
            />
            <Button onClick={() => void handleAsk()} disabled={loading}>
              {loading ? <Loader2 className="h-4 w-4 animate-spin" /> : "Ask"}
            </Button>
          </div>
          <div className="mt-4 flex flex-wrap gap-2">
            {suggestedQueries.map((q) => (
              <button
                key={q}
                onClick={() => { setQuery(q); void handleAsk(q); }}
                disabled={loading}
                className="text-xs rounded-full border bg-muted/40 hover:bg-primary-soft hover:border-primary/30 px-3 py-1.5 text-foreground transition disabled:opacity-50"
              >
                {q}
              </button>
            ))}
          </div>
        </CardContent>
      </Card>

      <div className="grid grid-cols-1 lg:grid-cols-4 gap-4 mt-6">
        <Card className="shadow-none border lg:col-span-3">
          <CardHeader>
            <span className="label-eyebrow">Answer</span>
            <CardTitle className="text-lg leading-snug mt-1">
              {answer?.summary ?? "Ask a question to get an AI-generated answer grounded in your farmer records."}
            </CardTitle>
          </CardHeader>
          <CardContent>
            {answer?.reasoning ? (
              <p className="text-sm text-muted-foreground mb-4">{answer.reasoning}</p>
            ) : null}
            <div className="rounded-lg border overflow-hidden">
              <table className="w-full text-sm">
                <thead>
                  <tr className="text-xs text-muted-foreground border-b bg-muted/40">
                    <th className="text-left font-medium px-4 py-2">Farmer</th>
                    <th className="text-left font-medium px-4 py-2">Region</th>
                    <th className="text-left font-medium px-4 py-2">Crop</th>
                    <th className="text-left font-medium px-4 py-2">Completeness</th>
                    <th className="text-left font-medium px-4 py-2">Source</th>
                  </tr>
                </thead>
                <tbody>
                  {matchedFarmers.length ? (
                    matchedFarmers.map((f) => (
                      <FarmerSheet key={f.id} farmer={f}>
                        <tr className="border-b last:border-0 cursor-pointer hover:bg-muted/30">
                          <td className="px-4 py-2.5 font-medium text-primary">{f.name}</td>
                          <td className="px-4 py-2.5 text-muted-foreground">{f.region}</td>
                          <td className="px-4 py-2.5 text-muted-foreground">{f.crop}</td>
                          <td className="px-4 py-2.5"><CompletenessBar value={f.completeness} /></td>
                          <td className="px-4 py-2.5 text-xs text-muted-foreground">{f.source}</td>
                        </tr>
                      </FarmerSheet>
                    ))
                  ) : (
                    <tr>
                      <td colSpan={5} className="px-4 py-8 text-center text-sm text-muted-foreground">
                        {loading ? "Generating answer…" : "No matching farmers yet."}
                      </td>
                    </tr>
                  )}
                </tbody>
              </table>
            </div>
            <div className="mt-4 flex items-center justify-between flex-wrap gap-2">
              <p className="text-xs text-muted-foreground">
                {answer?.sources?.length
                  ? `Generated from ${answer.sources.length} source(s): ${answer.sources.join(", ")}.`
                  : `Powered by OpenRouter · ${farmers.length} farmers loaded from Neo4j.`}
              </p>
              <div className="flex gap-2">
                <SaveInsightDialog query={query} />
                <Button variant="outline" size="sm" disabled={!matchedFarmers.length}>
                  <Download className="h-3.5 w-3.5 mr-1.5" /> Export CSV
                </Button>
              </div>
            </div>
          </CardContent>
        </Card>

        <Card className="shadow-none border">
          <CardHeader><CardTitle className="text-base">Saved insights</CardTitle></CardHeader>
          <CardContent className="space-y-3 text-sm">
            {[
              "Credit-ready farmers, Q2",
              "Nigerian millet growers — input gap",
              "Cooperative coverage by county",
              "Consent backlog (rolling)",
            ].map((s) => <SavedInsightDialog key={s} title={s} />)}
          </CardContent>
        </Card>
      </div>
    </div>
  );
}

function SaveInsightDialog({ query }: { query: string }) {
  return (
    <Dialog>
      <DialogTrigger asChild>
        <Button variant="outline" size="sm"><BookmarkPlus className="h-3.5 w-3.5 mr-1.5" /> Save insight</Button>
      </DialogTrigger>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>Save this insight</DialogTitle>
          <DialogDescription>Saved insights re-run automatically and appear on your dashboard.</DialogDescription>
        </DialogHeader>
        <div className="space-y-3">
          <div><Label className="text-xs">Title</Label><Input className="mt-1.5 h-9" defaultValue="Machakos maize · insurance gap" /></div>
          <div><Label className="text-xs">Query</Label><Textarea rows={3} className="mt-1.5 text-xs font-mono" defaultValue={query || "Which farmers are maize-ready but have no insurance coverage?"} /></div>
          <div><Label className="text-xs">Refresh</Label><Input className="mt-1.5 h-9" defaultValue="Daily at 06:00" /></div>
        </div>
        <DialogFooter><Button>Save insight</Button></DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

function SavedInsightDialog({ title }: { title: string }) {
  return (
    <Dialog>
      <DialogTrigger asChild>
        <button className="w-full text-left rounded-md border bg-muted/30 px-3 py-2 hover:bg-primary-soft transition cursor-pointer">
          <div className="font-medium text-foreground text-[13px]">{title}</div>
          <div className="text-[11px] text-muted-foreground mt-0.5">Refreshed yesterday</div>
        </button>
      </DialogTrigger>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>{title}</DialogTitle>
          <DialogDescription>Last refreshed yesterday at 06:00</DialogDescription>
        </DialogHeader>
        <div className="rounded-md border bg-muted/30 p-3 text-xs font-mono">
          MATCH (f:Farmer)-[:GROWS]-&gt;(c:Crop) WHERE c.name = 'Maize' AND NOT (f)-[:HAS_PRODUCT]-&gt;(:Insurance) RETURN f LIMIT 50
        </div>
        <DialogFooter>
          <Button variant="outline">Delete</Button>
          <Button>Open insight</Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
